name: Daily YouTube Summary

on:
  #schedule:
  #  - cron: '0 13 * * *'     # 1íšŒì°¨ 
  #  - cron: '0 1 * * *'      # 2íšŒì°¨
  workflow_dispatch:

jobs:
  run-daily-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install ffmpeg âœ…
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: ðŸ” Save cookies.txt from secret
        run: echo "${{ secrets.COOKIES_TXT }}" > cookies.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run youtube summaries
        run: python youtube_search.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
